
# install AWS CLI and download data
#curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
#unzip awscliv2.zip
#sudo ./aws/install

#aws s3 sync s3://openproblems-bio/public/explore  /tmp/public/ --no-sign-request